### ISSUE TITLE
Allow moving between recent rooms with keyboard shortcuts

### ISSUE THREAD

**Issue by melloc** [melloc/node-iamb#14]
In vim, `^I` and `^O` allow you to move around the jumplist, which contains recent locations in the file and other files. A similar feature for jumping to recently viewed rooms would be nice. To make it easy to toggle between views.

**Comment by jordanhendricks** [comment]
PR at https://github.com/melloc/node-iamb/pull/17.

This change implements a jump list for rooms and DMs. The lobby is appended to the list on startup, and subsequent `:dm` or `:join` commands will append the room in question to the list. Repeat movements are supported as well. For example, `5^I` will move the user 5 rooms forward in the list. Reaching the end or the beginning of the list will simply return the last or first item in the list, respectively.

As a part of this change, I implemented a data structure called a HistList, which can be used more generically for any type of history function that doesn't require branching. The HistList implements most of the details of how the jump list works, including handling appending to the list, fetching items from the list, and dealing with edge cases.
