### ISSUE TITLE
Implement horizontal split screen

### ISSUE THREAD

**Issue by melloc** [melloc/node-iamb#9]
In `vi`, you can split the screen horizontally with `:sp` and vertically with `:vsp`. It would be nice if `iamb` allowed something similar, so that people could layout conversations next to each other as they'd like. You could then resize/cycle/navigate through them with the `^W` vi commands.

**Comment by jordanhendricks** [comment]
Along with the normal typical `^W` commands, we should implement `^W-z` to zoom in on a single window, analogous to tmux's pane zoom feature (`^B-z`).

**Comment by melloc** [comment]
For now I'm just going to implement horizontal split screens, and return to do vertical splits at another time.
